package google.hates.pixel_unlocker

object Constants {
    val SHARED_PREF_FILE_NAME = "prefs"

    const val PREF_APP_SPECIFIC_SPOOFING = "PREF_APP_SPECIFIC_SPOOFING_"
    val PREF_SPOOF_FEATURES_LIST = "PREF_SPOOF_FEATURES_LIST"
    val PREF_DEVICE_TO_SPOOF = "PREF_DEVICE_TO_SPOOF"
    val PREF_STRICTLY_CHECK_GOOGLE_PHOTOS = "PREF_STRICTLY_CHECK_GOOGLE_PHOTOS"
    val PREF_OVERRIDE_ROM_FEATURE_LEVELS = "PREF_OVERRIDE_ROM_FEATURE_LEVELS"
    val PREF_ENABLE_VERBOSE_LOGS = "PREF_ENABLE_VERBOSE_LOGS"
    val PREF_SPOOF_ANDROID_VERSION_FOLLOW_DEVICE = "PREF_SPOOF_ANDROID_VERSION_FOLLOW_DEVICE"
    val PREF_SPOOF_ANDROID_VERSION_MANUAL = "PREF_SPOOF_ANDROID_VERSION_MANUAL"
}